require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'config.ru'
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'app/models/api/v1.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'app/views/movies/show.json.jbuilder'
    - 'app/helpers/application_helper.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/models/application_record.rb'
    - 'app/controllers/application_controller.rb'
Style/HashSyntax:
  Enabled: false
Metrics/MethodLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false   